volumes:
  db-data:
  gems:
  redis-data:

services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning --maxmemory-policy volatile-ttl
    volumes:
      - redis-data:/data

  web:
    build:
      context: .
      target: dev
    volumes:
      - .:/app:z
      - gems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - maildev
      - db
      - redis
    env_file: .env
    stdin_open: true
    tty: true

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"

  test:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    depends_on:
      - db
      - chrome-server
    environment:
      RAILS_ENV: test
    env_file: .env
    stdin_open: true
    tty: true

  chrome-server:
    image: selenium/standalone-chrome
    ports:
      - "7900:7900"
