volumes:
  db-data:
  storage:

services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env

  web:
    image: sitarane/inseason:0.3
    volumes:
      - storage:/app/storage
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file: .env
    environment:
      RAILS_ENV: production
