volumes:
  db-data:
  storage:
  log:
  redis-data:

services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped

  web:
    image: sitarane/inseason:0.17
    volumes:
      - storage:/app/storage
      - log:/app/log
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      RAILS_ENV: production
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning --maxmemory-policy volatile-ttl
    volumes:
      - redis-data:/data
    restart: unless-stopped
