volumes:
  db-data:
  storage:
  log:

  staging-db-data:
  staging-storage:
  staging-log:

networks:
  staging:
  production:

services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - production

  web:
    image: sitarane/inseason:0.12-alpine
    volumes:
      - storage:/app/storage
      - log:/app/log
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file: .env
    environment:
      RAILS_ENV: production
    networks:
      - production


  staging:
    image: sitarane/inseason:0.13
    volumes:
      - staging-storage:/app/storage
      - staging-log:/app/log
    ports:
      - "3002:3000"
    depends_on:
      - staging-db
    env_file: .env
    environment:
      RAILS_ENV: staging
      SECRET_KEY_BASE: 914b724963902578d48d8d7b004292991904a71221c52e5595075f97d8b713667a69e2563f2933d3a8e8debf3ea32bbe76fbd7705450e303976a97ff681ba661
    networks:
      - staging

  staging-db:
    image: postgres:15
    volumes:
      - staging-db-data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - staging
